### ISSUE TITLE
Formátování 

### ISSUE THREAD

**Issue by fan1x** [MichalKyjovsky/CourseWorkNPRG031#12]
https://github.com/MichalKyjovsky/CourseWorkNPRG030/blob/f6b039e26471893be61828be1f3be5c6bf3c3ca9/TextHelper/TxTHlpr.cs#L308

**Comment by fan1x** [comment]
V daném souboru je na něktrých místech rozbité formátování (zarovnání). ¨
Například také: https://github.com/MichalKyjovsky/CourseWorkNPRG030/blob/f6b039e26471893be61828be1f3be5c6bf3c3ca9/TextHelper/TxTHlpr.cs#L337

**Comment by MichalKyjovsky** [comment]
Už by to mělo být v pořádku

**Comment by fan1x** [comment]
Není 😞 Např: https://github.com/MichalKyjovsky/CourseWorkNPRG030/blob/30c9048a17eec75c6a9b3b9ef5b5ca8de4aea103/TextHelper/TxTHlpr.cs#L356
