### ISSUE TITLE
Program nepadá na nevalidních vstupech

### ISSUE THREAD

**Issue by fan1x** [MichalKyjovsky/CourseWorkNPRG031#13]

**Comment by fan1x** [comment]
Je potřeba všechny vstupy ozkoušet, není to žádná věda. Prostě ozkoušet nějaké možné okrajové příklady (normální, super dlouhý, super krátky, prázdný, ...)

**Comment by MichalKyjovsky** [comment]
Ohledně vstupů se bavíme o psaní do třídy TextBoxInterface(RichTextBox) nebo do polí find , replace etc.?

**Comment by fan1x** [comment]
Asi uz v pohode...
