### ISSUE TITLE
vyřešit kodování

### ISSUE THREAD

**Issue by fan1x** [MichalKyjovsky/CourseWorkNPRG031#9]
![error2](https://user-images.githubusercontent.com/2750870/64379133-8df18700-d02e-11e9-93db-1b673460e9c1.png)

**Comment by fan1x** [comment]
Teď vyhledávání `česká republika` nevrátí nic - Page you are looking for may does not exist.
Check correctness of your request.

**Comment by fan1x** [comment]
Neď to nevrátí nic ani pro "Czech Republic", což je divné. Vrátil bych to zpátky a poladil kódování v programu...

**Comment by MichalKyjovsky** [comment]
Funguje i čeština
